{
  "openapi": "3.1.0",
  "info": {
    "title": "CS2KZ API",
    "description": "",
    "contact": {
      "name": "AlphaKeks",
      "email": "alphakeks@dawn.sh"
    },
    "license": {
      "name": "GPL-3.0",
      "url": "https://www.gnu.org/licenses/gpl-3.0.en.html"
    },
    "version": "0.0.0-dev"
  },
  "servers": [
    {
      "url": "https://api.cs2kz.org"
    }
  ],
  "paths": {
    "/leaderboards/rating": {
      "get": {
        "tags": [
          "Leaderboards"
        ],
        "summary": "Global Player Rating Leaderboard",
        "description": "This endpoint returns the highest rated players in KZ.",
        "operationId": "get_rating_leaderboard"
      }
    },
    "/leaderboards/records/{leaderboard}": {
      "get": {
        "tags": [
          "Leaderboards"
        ],
        "summary": "Global World Record Leaderboard",
        "description": "This endpoint returns the players with the most World Records.",
        "operationId": "get_records_leaderboard"
      }
    },
    "/records": {
      "get": {
        "tags": [
          "Records"
        ],
        "summary": "Records",
        "description": "This endpoint returns the latest records.",
        "operationId": "get_records"
      }
    },
    "/records/{record_id}": {
      "get": {
        "tags": [
          "Records"
        ],
        "summary": "Records by ID",
        "description": "This endpoint returns a specific record by its API-assigned ID.",
        "operationId": "get_record"
      }
    },
    "/maps": {
      "put": {
        "tags": [
          "Maps"
        ],
        "summary": "Map Submission",
        "description": "This endpoint can be used to submit KZ maps to the API. All maps must be\nuploaded to Steam's Community Workshop and the API will source their name\nfrom there. If you plan on submitting your map for approval, make sure it\nfollows [the rules].\n\n[the rules]: https://docs.cs2kz.org/mapping/approval#rules",
        "operationId": "create_map",
        "security": [
          {
            "session_auth": []
          }
        ]
      }
    },
    "/maps/{game}": {
      "get": {
        "tags": [
          "Maps"
        ],
        "summary": "Global KZ Maps",
        "description": "This endpoint returns the latest KZ maps.",
        "operationId": "get_maps"
      }
    },
    "/maps/{map_id}": {
      "get": {
        "tags": [
          "Maps"
        ],
        "summary": "Global KZ Maps by ID",
        "description": "This endpoint returns a specific KZ map by its API-assigned ID.",
        "operationId": "get_map"
      },
      "patch": {
        "tags": [
          "Maps"
        ],
        "summary": "Update your Map",
        "description": "This endpoint can be used to make the API aware of changes to your map as\nwell as update metadata such as mapper information or descriptions. If your\nmap is currently work-in-progress and you uploaded a new version to Steam's\nCommunity Workshop, you must send a request to this endpoint to make the API\naware of it.",
        "operationId": "update_map",
        "security": [
          {
            "session_auth": [
              "update-maps"
            ]
          }
        ]
      }
    },
    "/maps/{map_id}/state": {
      "put": {
        "tags": [
          "Maps"
        ],
        "summary": "Update a map's state",
        "description": "This endpoint can be used by the Map Approval Team to approve or reject\nsubmitted maps.",
        "operationId": "update_map_state",
        "security": [
          {
            "session_auth": [
              "update-maps"
            ]
          }
        ]
      }
    },
    "/servers": {
      "get": {
        "tags": [
          "Servers"
        ],
        "summary": "Global KZ Servers",
        "description": "This endpoints returns KZ servers registered with the API. Servers which are\ncurrently online and connected to the API will contain a `connection_info`\nobject with real-time information about the map they're currently hosting\nand who's playing on them.",
        "operationId": "get_servers"
      },
      "post": {
        "tags": [
          "Servers"
        ],
        "summary": "Register your KZ server",
        "description": "This endpoint can be used to register KZ servers with the API. If you are\na server owner, please make sure your server follows [the rules].\n\n[the rules]: https://docs.cs2kz.org/servers/approval#rules",
        "operationId": "create_server",
        "security": [
          {
            "session_auth": []
          }
        ]
      }
    },
    "/servers/{server_id}": {
      "get": {
        "tags": [
          "Servers"
        ],
        "summary": "Global KZ Servers by ID",
        "description": "Returns a specific KZ server by its API-assigned ID.",
        "operationId": "get_server"
      },
      "patch": {
        "tags": [
          "Servers"
        ],
        "summary": "Update your KZ Server",
        "description": "This endpoint can be used by server owners to update the metadata of their\nservers, such as IP/port.",
        "operationId": "update_server",
        "security": [
          {
            "session_auth": [
              "modify-server-metadata"
            ]
          }
        ]
      }
    },
    "/servers/{server_id}/access-key": {
      "put": {
        "tags": [
          "Servers"
        ],
        "summary": "Generate a new access key",
        "description": "This endpoint can be used by server owners and admins to generate a new\naccess key for a server. This immediately invalidates the old key and cuts\noff the server if it is currently connected to the API.",
        "operationId": "reset_server_access_key",
        "security": [
          {
            "session_auth": [
              "reset-server-access-keys"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Servers"
        ],
        "summary": "Delete a server's API key",
        "description": "This endpoint can be used by admins to delete a server's API key. This\nimmediately invalidates it and cuts off the server if it is currently\nconnected to the API.",
        "operationId": "delete_server_access_key",
        "security": [
          {
            "session_auth": [
              "delete-server-access-keys"
            ]
          }
        ]
      }
    },
    "/bans": {
      "get": {
        "tags": [
          "Bans"
        ],
        "summary": "Player Bans",
        "description": "This endpoint returns the latest player bans created by `POST /bans`.",
        "operationId": "get_bans"
      },
      "post": {
        "tags": [
          "Bans"
        ],
        "summary": "Ban a player",
        "description": "This endpoint can be used to restrict players from submitting records or\njumpstats to the API. Servers will also be informed about banned players\nwhen they join.",
        "operationId": "create_ban",
        "security": [
          {
            "session_auth": [
              "create-bans"
            ]
          }
        ]
      }
    },
    "/bans/{ban_id}": {
      "get": {
        "tags": [
          "Bans"
        ],
        "summary": "Player Bans by ID",
        "description": "This endpoint returns information about a specific ban.",
        "operationId": "get_ban"
      },
      "delete": {
        "tags": [
          "Bans"
        ],
        "summary": "Revert a Ban",
        "description": "This endpoint can be used to revert a ban (\"unban\" a player). Only active\nbans can be reverted and a player can only have one active ban at a time.",
        "operationId": "revert_ban",
        "security": [
          {
            "session_auth": [
              "revert-bans"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Bans"
        ],
        "summary": "Update an existing Ban",
        "description": "This endpoint can be used to update the details of a ban, such as the ban\nreason or duration.\n\n**Do not use this endpoint to revert bans! Use `DELETE /bans/{ban_id}`\ninstead.**",
        "operationId": "update_ban",
        "security": [
          {
            "session_auth": [
              "update-bans"
            ]
          }
        ]
      }
    },
    "/players": {
      "get": {
        "tags": [
          "Players"
        ],
        "summary": "KZ Players",
        "description": "This endpoint returns information about players who have joined KZ servers\nbefore.",
        "operationId": "get_players"
      }
    },
    "/players/{player_id}": {
      "get": {
        "tags": [
          "Players"
        ],
        "summary": "KZ Players by SteamID",
        "description": "This endpoint returns a specific player by their SteamID.",
        "operationId": "get_player"
      }
    },
    "/players/{player_id}/preferences": {
      "get": {
        "tags": [
          "Players"
        ],
        "summary": "Player Preferences",
        "description": "This endpoint returns the in-game preferences of a specific player.",
        "operationId": "get_player_preferences"
      },
      "put": {
        "tags": [
          "Players"
        ],
        "summary": "Update Player Preferences",
        "description": "This endpoint can be used to update your in-game preferences without joining\na server and doing it manually there.",
        "operationId": "update_player_preferences",
        "security": [
          {
            "session_auth": []
          }
        ]
      }
    },
    "/users": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "API Users",
        "description": "This endpoint returns information about users that have logged into the API\nbefore.",
        "operationId": "get_users"
      }
    },
    "/users/{user_id}": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "API Users by SteamID",
        "description": "This endpoint returns information about a specific user by their SteamID.",
        "operationId": "get_user"
      }
    },
    "/users/{user_id}/email": {
      "put": {
        "tags": [
          "Users"
        ],
        "summary": "Update your Email address",
        "description": "This endpoint can be used to update your email address. The API will use\nthis for sending notifications, for example if you are a server owner.",
        "operationId": "update_user_email",
        "security": [
          {
            "session_auth": []
          }
        ]
      },
      "delete": {
        "tags": [
          "Users"
        ],
        "summary": "Delete your Email address",
        "description": "This endpoint can be used to completely delete your email address from the\nAPI. It will no longer be able to send you notifications anymore.",
        "operationId": "delete_user_email",
        "security": [
          {
            "session_auth": []
          }
        ]
      }
    },
    "/users/{user_id}/permissions": {
      "put": {
        "tags": [
          "Users"
        ],
        "summary": "Update a user's permissions",
        "description": "This endpoint can be used to edit other users' permissions.",
        "operationId": "update_user_permissions",
        "security": [
          {
            "session_auth": [
              "modify-user-permissions"
            ]
          }
        ]
      }
    },
    "/users/{user_id}/server-budget": {
      "put": {
        "tags": [
          "Users"
        ],
        "summary": "Update a user's server budget",
        "description": "This endpoint can be used to set a user's server budget (how many servers\nthey are allowed to create).",
        "operationId": "update_user_server_budget",
        "security": [
          {
            "session_auth": [
              "modify-server-budgets"
            ]
          }
        ]
      }
    },
    "/mappers/{user_id}": {
      "put": {
        "tags": [
          "Mappers"
        ],
        "summary": "Mark a user as a mapper",
        "description": "This endpoint can be used to mark a user as a \"mapper\". This will allow them\nto use the `PUT /maps` endpoint.",
        "operationId": "create_mapper",
        "security": [
          {
            "session_auth": [
              "grant-create-maps"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Mappers"
        ],
        "summary": "Mark a user as a non-mapper",
        "description": "This endpoint can be used to mark a user as not a \"mapper\". This will\nprevent them from using the `PUT /maps` endpoint.",
        "operationId": "delete_mapper",
        "security": [
          {
            "session_auth": [
              "grant-create-maps"
            ]
          }
        ]
      }
    },
    "/auth/web/login": {
      "get": {
        "tags": [
          "User Authentication"
        ],
        "summary": "Login with Steam",
        "description": "This endpoint will redirect you to Steam for login.",
        "operationId": "web_login"
      }
    },
    "/auth/web/logout": {
      "get": {
        "tags": [
          "User Authentication"
        ],
        "summary": "Logout",
        "description": "This endpoint can be used to delete your current, and optionally all other,\nactive session(s).",
        "operationId": "web_logout",
        "security": [
          {
            "session_auth": []
          }
        ]
      }
    },
    "/events": {
      "get": {
        "tags": [
          "Events"
        ],
        "summary": "Real-Time events",
        "description": "Returns an [SSE] response.\n\n[SSE]: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events",
        "operationId": "events"
      }
    },
    "/plugin/versions": {
      "get": {
        "tags": [
          "Plugin"
        ],
        "summary": "GOKZ/cs2kz-metamod versions",
        "description": "This endpoints returns metadata about official releases of the GOKZ and\ncs2kz-metamod projects.",
        "operationId": "get_plugin_versions"
      },
      "post": {
        "tags": [
          "Plugin"
        ],
        "summary": "Register a new GOKZ/cs2kz-metamod version",
        "description": "This endpoint is used by GitHub CI to inform the API of new plugin versions.",
        "operationId": "create_plugin_version",
        "security": [
          {
            "api_key": []
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "api_key": {
        "type": "http",
        "scheme": "bearer"
      },
      "session_auth": {
        "type": "apiKey",
        "in": "header",
        "name": "kz-auth"
      }
    }
  },
  "tags": [
    {
      "name": "Leaderboards"
    },
    {
      "name": "Records"
    },
    {
      "name": "Maps"
    },
    {
      "name": "Servers"
    },
    {
      "name": "Bans"
    },
    {
      "name": "Players"
    },
    {
      "name": "Users"
    },
    {
      "name": "Mappers"
    },
    {
      "name": "User Authentication",
      "description": "OpenID 2.0 authentication with Steam"
    },
    {
      "name": "Events",
      "description": "Real-Time events via SSE"
    },
    {
      "name": "Plugin",
      "description": "GOKZ/cs2kz-metamod"
    }
  ]
}
